// Dev helper: node tools/shot.mjs [url] [rootdir] — boots the game, clicks through, draws level 1, screenshots to test-results/dev-*.png
import { chromium } from 'playwright';
import { spawn } from 'child_process';
const url = process.argv[2] || 'http://localhost:8089/';
const srv = spawn('node', ['dev.js', process.argv[3] || '.'], { env: { ...process.env, PORT: '8089' }, stdio: 'ignore' });
await new Promise(r => setTimeout(r, 600));
const b = await chromium.launch(), p = await b.newPage({ viewport: { width: 900, height: 600 } });
const errs = [];
p.on('console', m => { if (m.type() == 'error' || m.type() == 'warning') errs.push(m.type() + ': ' + m.text()); });
p.on('pageerror', e => errs.push('pageerror: ' + e.message));
await p.goto(url); await p.waitForTimeout(500);
await p.screenshot({ path: 'test-results/dev-title.png' });
await p.click('[data-a=go]'); await p.waitForTimeout(200);
await p.screenshot({ path: 'test-results/dev-select.png' });
await p.click('[data-a=lv][data-v="0"]'); await p.waitForTimeout(200);
await p.screenshot({ path: 'test-results/dev-draw.png' });
await p.click('[data-a=c][data-v="1"]');
const [x0, y0] = await p.evaluate(() => __prism.toScreen(10, 12)), [x1, y1] = await p.evaluate(() => __prism.toScreen(22, 12));
await p.mouse.move(x0, y0); await p.mouse.down();
for (let i = 1; i <= 10; i++) await p.mouse.move(x0 + (x1 - x0) * i / 10, y0 + (y1 - y0) * i / 10);
await p.mouse.up(); await p.waitForTimeout(100);
console.log('strokes', await p.evaluate(() => __prism.strokes.length));
await p.click('[data-a=p]');
await p.waitForTimeout(2500); await p.screenshot({ path: 'test-results/dev-play.png' });
await p.waitForSelector('[data-a=nx]', { timeout: 8000 }).catch(() => console.log('no win overlay'));
await p.screenshot({ path: 'test-results/dev-win.png' });
console.log('progress', await p.evaluate(() => localStorage.prism26_progress));
console.log('errors:', errs);
await b.close(); srv.kill();
